modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="${author}" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="${modid}" #mandatory

version="${version}" #mandatory

displayName="${modName}" #mandatory

description='''${desc}'''

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion},)"
    ordering="NONE"
    side="BOTH"